In [1]:
import numpy as np


In [21]:
ar1 = np.array([[1,2,3],[2,3,4],[4,5,6]])
ar2 = np.array([[3],[2],[1]])


print("ar1 shape:" + str(ar1.shape))
print("ar2 shape:" + str(ar2.shape))

print(ar1 * ar2)

ar1 shape:(3, 3)
ar2 shape:(3, 1)
[[3 6 9]
 [4 6 8]
 [4 5 6]]


In [7]:
mul = np.dot(ar1, ar2)
print("multiply:" + str(mul))
print("shape:" + str(mul.shape))
print("before squeeze:" + str(mul))

mul = np.squeeze(mul)
print("shape:" + str(mul.shape))
print(mul)

multiply:[[10]]
shape:(1, 1)
before squeeze:[[10]]
shape:()
10


In [9]:
print("hello {}".format("james"))

hello james


In [10]:
ar3 = np.array([1,2,3])
val = np.mean(ar3)
print(val.shape)
print(val)

()
2.0


In [11]:
cost = []
cost.append(1.0)

In [13]:
print(cost)

[1.0]


In [15]:
val = ar1[:,1]
print(val)

[2]


In [18]:
val = ar1[0,2]
print(val)

3
