## sigmoid function

In [3]:
import math

def basic_sigmoid(x):
    return 1/(1+math.exp(-x))


n = basic_sigmoid(3)
print(n)

0.9525741268224334


## sigmoid function using numpy

In [12]:
import numpy as np
x = np.array([1,2,3])
print(x)
print(x+3)

sigX = np.exp(x)
print(sigX)


[1 2 3]
[ 2.71828183  7.3890561  20.08553692]
[4 5 6]


In [15]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

print(x)
print(sigmoid(x))

[1 2 3]
[0.73105858 0.88079708 0.95257413]


## sigmoid gradient 

## Reshape Arrays

In [24]:
def img2vector(image):
    vector = image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)
    return vector

image = np.array(
    [
        [
         [1,1],
         [2,2],
         [3,3]
        ],
        [
         [10,10],
         [20,20],
         [30,30]
        ],
        [
         [100,100],
         [200,200],
         [300,300]
        ] 
    ]
)

print(image)

vector = img2vector(image)
print("reshape to")
print(vector)

[[[  1   1]
  [  2   2]
  [  3   3]]

 [[ 10  10]
  [ 20  20]
  [ 30  30]]

 [[100 100]
  [200 200]
  [300 300]]]
reshape to
[[  1]
 [  1]
 [  2]
 [  2]
 [  3]
 [  3]
 [ 10]
 [ 10]
 [ 20]
 [ 20]
 [ 30]
 [ 30]
 [100]
 [100]
 [200]
 [200]
 [300]
 [300]]


## Normalized Rows